### ISSUE TITLE
TypeError: <class 'mahjong_utils.shanten.models.CommonShantenResult'> is not a generic class

### ISSUE THREAD

**Issue by shinkuan** [ssttkkl/mahjong-utils#4]
Error when trying to import mahjong_utils:
```
Traceback (most recent call last):
  File "T:\get_reward\get_reward.py", line 4, in <module>
    import mahjong_utils
  File "T:\get_reward\VENV\lib\site-packages\mahjong_utils\__init__.py", line 1, in <module>
    from . import hora
  File "T:\get_reward\VENV\lib\site-packages\mahjong_utils\hora\__init__.py", line 1, in <module>
    from .hora import *
  File "T:\get_reward\VENV\lib\site-packages\mahjong_utils\hora\hora.py", line 10, in <module>
    from mahjong_utils.shanten import ShantenResult
  File "T:\get_reward\VENV\lib\site-packages\mahjong_utils\shanten\__init__.py", line 1, in <module>
    from .models import *
  File "T:\get_reward\VENV\lib\site-packages\mahjong_utils\shanten\models.py", line 262, in <module>
    class RegularShantenResult(CommonShantenResult[RegularHandPattern]):
  File "T:\get_reward\VENV\lib\site-packages\pydantic\main.py", line 591, in __class_getitem__
    raise TypeError(f'{cls} is not a generic class')
TypeError: <class 'mahjong_utils.shanten.models.CommonShantenResult'> is not a generic class
```
Tested under windows 11, Python 3.10.6 and Python 3.11.4

**Comment by ssttkkl** [comment]
Failed to reproduce this problem at all my environments (Python 3.10/3.11, Windows 10/macOS 13). However, there actually has a problem with my previous version. Upgrade to version 0.6.0 and try again.
If still not working, try `pip install -r requirements.txt`.
